# Generated by Django 4.0.3 on 2022-03-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_text', models.CharField(blank=True, max_length=500, null=True)),
                ('hate_label', models.FloatField(blank=True)),
                ('offn_label', models.FloatField(blank=True)),
                ('prfn_label', models.FloatField(blank=True)),
                ('not_label', models.FloatField(blank=True)),
            ],
        ),
    ]
